### ISSUE TITLE
Mix of new and old Ohai Filesystem data

### ISSUE THREAD

**Issue by rylarson** [chefspec/fauxhai#300]
Fauxhaui appears to have a mix of Chef 12 and Chef 13 Ohai Filesystem/Filesystem2 data. See: https://docs.chef.io/deprecations_ohai_filesystem.html

For example, the Oracle 7.1 dumps have the old data structure, and the Oracle 7.3 dumps have the new data. There are also lots of other dumps that have the old data structure.

How does something like breaking ohai data structure changes translate to semver for Fauxhai?

**Comment by tas50** [comment]
The deprecated dumps are Chef 12. If you're using the latest Fauxhai you'll get warnings when you try to use that old platform data. Also the platforms documentation file only includes the non-deprecated files. In the next major release all those old platforms will go away since there's no way for me to install / dump all those platforms again.
