### ISSUE TITLE
Gem specification needs to tighten dependency on Chef

### ISSUE THREAD

**Issue by ncs-alane** [chefspec/fauxhai#305]
The gem specification as of v5.3.0 depends on Chef >= 12, but the Amazon platform information specifies that the Amazon platform family as Amazon, which is only accurate as of Chef 13 (via Ohai 13.3). I suggest that the dependency should be patched to Chef ~> 13. 

https://github.com/chefspec/fauxhai/blob/v5.3.0/fauxhai.gemspec#L24
https://github.com/chef/ohai/pull/971

**Comment by tas50** [comment]
Chef is a development dependency for dumping new data not a runtime dependency in any way related to the data that is currently within Fauxhai. It's still at >=12 because many users want to be able to use Fauxhai to collect custom data within their environments still running Chef 12. Next year when Chef 12 goes EOL I will bump that to >=13, but for now it's the desired versions string.
