### ISSUE TITLE
ship minor platform_versions

### ISSUE THREAD

**Issue by yeoldegrove** [chefspec/fauxhai#341]
In 6cc44b32ded7d869543d586b15bfadfee59e00c2 and 4dd37413f7773e8d37f32daa1f72b011d0f54e64 and 89af55e4eecf9675bb93e9ee17d3f8b244389215 the minor `platform_versions` were removed.

We have the usecase to test ChefSpec against these minor versions.
The reason for that is that (at least at suse) there are/were a lot of changes in e.g. the SLES12 release.
These changes include package lists, config files, kernel parameters...

Please consider reintroducing this.

**Comment by yeoldegrove** [comment]
Would this code be an alternative or the new way to acchieve testing against a minor `platform_version` ?

```
describe 'cookbook::recipe' do
  platform 'suse', '12'
  automatic_attributes['node']['platform_version']
[..]
end
```

If this is the case, the chefspec documentation should clearly state that.

**Comment by lamont-granquist** [comment]
Maintenance and upgrading of the minor platform_versions is too much of a headache.  Nobody does it so you wind up with Chef 11 ohai output for stuff.  In order to stay current on reasonably recent ohai output the support matrix has to be reduced.

And that is the way to fix it, you could submit a PR to the chefspec project to add that doc.
